Performance\Domain\Author:
  type: entity
  repositoryClass: \Performance\Infrastructure\Database\DoctrineAuthorRepository
  table: authors
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
      length: 255
    password:
      type: string
      length: 255
    photo:
      type: text